export const FETCH_WISH_LIST = 'FETCH_WISH_LIST';
export const FETCH_WISH_LIST_SUCCESS = 'FETCH_WISH_LIST_SUCCESS';
export const FETCH_WISH_LIST_FAILURE = 'FETCH_WISH_LIST_FAILURE';

export const ADD_TO_WISH_LIST = 'ADD_TO_WISH_LIST';
export const ADD_TO_WISH_LIST_SUCCESS = 'ADD_TO_WISH_LIST_SUCCESS';

export const REMOVE_FROM_WISH_LIST = 'REMOVE_FROM_WISH_LIST';
export const REMOVE_FROM_WISH_LIST_SUCCESS = 'REMOVE_FROM_WISH_LIST_SUCCESS';